name: resumesux_application
description: Contracts and usecases for ResumesUX clean architecture
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  fpdart: ^1.2.0
  resumesux_domain:
    git:
      url: https://github.com/staylorx/resumesux_domain
  args: ^2.5.0
  dotenv: ^4.2.0
  http: ^1.2.0
  yaml: ^3.1.0

dev_dependencies:
  dart_arch_test: ^0.3.1
  lints: ^6.0.0
  path: ^1.8.3
  test: ^1.28.0
  mocktail: ^1.0.4
